<?php if ($this->transportadora) :?> 
	<p>Tem certeza que deseja deletar a transportadora
	  '<?php echo $this->escape($this->transportadora->nome); ?>'? 
	</p> 
	<form action="<?php echo $this->url(array('action'=>'del')); ?>" method="post"> 
		<div> 
		  <input type="hidden" name="id" value="<?php echo $this->transportadora->id; ?>" /> 
		  <input type="submit" class="button"  name="del" value="Sim" /> 
		  <input type="submit" class="button2" name="del" value="Não" /> 
		</div> 
	</form> 
<?php else: ?> 
	<p>Transportadora não pôde ser encontrada.</p> 
<?php endif;?> 