<?php if ($this->group) :?>
	<p>Tem certeza que deseja deletar o grupo
	  '<?php echo $this->escape($this->group->name); ?>'?
	</p> 
	<form action="<?php echo $this->url(array('action'=>'del')); ?>" method="post"> 
		<div> 
		  <input type="hidden" name="id" value="<?php echo $this->group->id; ?>" />
		  <input type="submit" class="button"  name="del" value="Sim" /> 
		  <input type="submit" class="button2" name="del" value="Não" /> 
		</div> 
	</form> 
<?php else: ?> 
	<p>Grupo não pôde ser encontrado.</p>
<?php endif;?> 