<table class="tableItems"> 
<tr> 
    <th>Cor</th> 
    <th>&nbsp;<a href="/cores/add"><img src="/images/add4.png" alt="Adicionar" title="Adicionar" /></a></th> 
</tr> 
<?php foreach($this->cor as $cor) : ?>
<?php @$style=($style=='evenRow') ? 'oddRow' : 'evenRow' ;?> 
<tr class="<?php echo @$style;?>"> 
    <td>&nbsp;<?php echo $this->escape($cor->cor);?>&nbsp;</td> 
    <td style="min-width:30pt;text-align: right;background-color: transparent;">
        <a href="/cores/edit/id/<?php echo $cor->id;?>"><img src="/images/edit.png" alt="Editar" title="Editar" /></a> 
        <a href="/cores/del/id/<?php echo $cor->id;?>"><img src="/images/del.png" alt="Excluir" title="Excluir" /></a> 
	</td>
</tr> 
<?php endforeach; ?> 
</table> 