<?php if ($this->estado) :?> 
	<p>Tem certeza que deseja deletar o estado
	  '<?php echo $this->escape($this->estado->estado); ?>'? 
	</p> 
	<form action="<?php echo $this->url(array('action'=>'del')); ?>" 
	method="post"> 
		<div> 
		  <input type="hidden" name="id" value="<?php echo $this->estado->id; ?>" /> 
		  <input type="submit" class="button"  name="del" value="Sim" /> 
		  <input type="submit" class="button2" name="del" value="Não" /> 
		</div> 
	</form> 
<?php else: ?> 
	<p>O Estado não pode ser encontrado.</p> 
<?php endif;?> 