<table class="tableItems">
	<th>&nbsp;Estado&nbsp;</th>
	<th>&nbsp;Sigla&nbsp;</th>
	 <th>&nbsp;
    	<a href="<?php echo $this->url(array('action'=>'add'));?>">
    		<img src="/images/add4.png" alt="Adicionar" title="Adicionar" />
    	</a>
    </th> 

	<?php foreach($this->estados as $estado) :?>
	<?php @$style=($style=='evenRow') ? 'oddRow' : 'evenRow' ;?> 
	<tr class="<?php echo @$style;?>"> 
			<td>&nbsp;<?php echo $this->escape($estado->estado);?>&nbsp;</td>
			<td>&nbsp;<?php echo $this->escape($estado->sigla);?>&nbsp;</td>
			<td style="min-width:30pt;text-align: right;background-color: transparent;">
		        <a href="<?php echo $this->url(array('controller'=>'estados',  
		            'action'=>'edit', 'id'=>$estado->id));?>"><img src="/images/edit.png" alt="Editar" title="Editar" /></a> 
		            
		        <a href="<?php echo $this->url(array('controller'=>'estados',  
		            'action'=>'del', 'id'=>$estado->id));?>"><img src="/images/del.png" alt="Excluir" title="Excluir" /></a> 
		    </td> 
		</tr>
	<?php endforeach; ?>
</table>
