<br/>	
<br/>

<label for="suggest">Pesquise:</label>
<input type="text" size="50" id="suggest"/>
<input type="button" class="button" value="Localizar" id="search" />

<div id="results"></div>

<br/>
<br/>
<br/>


<table id="tabelaCidades">
    <thead>
        <tr>
            <th>Cidade</th>
            <th>Estado</th>
            <th><a href="/cidades/new">
                <img src="/images/add4.png" alt="Adicionar" title="Adicionar" />
                </a>
            </th>
            <th>&nbsp;</th>
        </tr>
    </thead>
    <tbody>
        
    </tbody>
</table>
