<table class="tableItems"> 
	<tr> 
	    <th>Fantasia</th> 
	    <th>Nome Oficial</th>
	    <th>Cidade</th>
	    <th>Estado</th>
	    
	    <th>&nbsp;<a href="/fabricas/new"><img src="/images/add4.png" alt="Adicionar" title="Adicionar" /></a></th> 
	</tr> 
	<?php foreach($this->fabrica as $fabrica) : ?>
	<?php @$style=($style=='evenRow') ? 'oddRow' : 'evenRow' ;?> 
	<tr class="<?php echo @$style;?>"> 
	    <td>&nbsp;<?php echo $this->escape($fabrica->fantasia);?>&nbsp;</td> 
	    <td>&nbsp;<?php echo $this->escape($fabrica->nome);?>&nbsp;</td> 
	    <td>&nbsp;<?php echo $this->escape($fabrica->findParentRow('Cidades')->cidade);?>&nbsp;</td>  
	    <td>&nbsp;<?php echo $this->escape(
	    							$fabrica
	        							->findParentRow('Cidades')
	    								->findParentRow('Estados')
	    								->sigla
	    							);
	    			?>&nbsp;</td>  
	    
	    
	    
	    <td style="min-width:30pt;text-align: right;background-color: transparent;">
	        <a href="<?php echo $this->url(array('action'=>'edit'))?>/id/<?php echo $fabrica->id;?>"><img src="/images/edit.png" alt="Editar" title="Editar" /></a> 
	        <a href="<?php echo $this->url(array('action'=>'del'))?>/id/<?php echo $fabrica->id;?>"><img src="/images/del.png" alt="Excluir" title="Excluir" /></a> 
		</td>
	</tr> 
	<?php endforeach; ?> 
</table> 