<?php if ($this->produto) :?> 
	<p>Tem certeza que deseja deletar o produto
	  '<?php echo $this->escape($this->produto->nome); ?>' (ref: <?php echo $this->escape($this->produto->referencia); ?>) ? 
	</p> 
	<form action="<?php echo $this->url(array('action'=>'del')); ?>" method="post"> 
		<div> 
		  <input type="hidden" name="id" value="<?php echo $this->produto->id; ?>" /> 
		  <input type="submit" class="button"  name="del" value="Sim" /> 
		  <input type="submit" class="button2" name="del" value="Não" /> 
		</div> 
	</form> 
<?php else: ?> 
	<p>Produto não pôde ser encontrado.</p> 
<?php endif;?> 