<table class="tableItems"> 
	<tr> 
	    <th>&nbsp;Produto&nbsp;</th>
	    <th>&nbsp;Ref.&nbsp;</th> 
	    <th>&nbsp;Ref. Cliente&nbsp;</th>
	    <th>&nbsp;Tipo&nbsp;</th> 
	    <th>&nbsp;Estação&nbsp;</th> 
	    <th>&nbsp;Grupo&nbsp;</th> 

	    
	    <th>&nbsp;<a href="/produtos/new">
	    			<img src="/images/add4.png" alt="Adicionar" title="Adicionar" />
	    		</a>
	    	</th> 
	</tr> 
	<?php foreach($this->produtos as $produto) : ?>
    	<?php @$style=($style=='evenRow') ? 'oddRow' : 'evenRow' ;?> 
        	<tr class="<?php echo @$style;?>"> 
        	    <td>&nbsp;<?php echo $this->escape($produto->nome);?>&nbsp;</td> 
        	    <td>&nbsp;<?php echo $this->escape($produto->referencia);?>&nbsp;</td> 
        	    <td>&nbsp;<?php echo $this->escape($produto->referenciaCliente);?>&nbsp;</td> 
        	    <td>&nbsp;<?php echo $this->escape($produto->findParentRow('TipoProduto')->tipo);?>&nbsp;</td>  
        	    <td>&nbsp;<?php echo $this->escape($produto->findParentRow('Estacoes')->estacao);?>&nbsp;</td>  
        	    <td>&nbsp;<?php echo $this->escape($produto->findParentRow('Divisoes')->divisao);?>&nbsp;</td>  
         
        	    
        	    <td style="min-width:30pt;text-align: right;background-color: transparent;">
        	        <a href="<?php echo $this->url(array('action'=>'edit'))?>/id/<?php echo $produto->id;?>">
        	        	<img src="/images/edit.png" alt="Editar" title="Editar" /></a> 
        	        <a href="<?php echo $this->url(array('action'=>'del'))?>/id/<?php echo $produto->id;?>">
        	        	<img src="/images/del.png" alt="Excluir" title="Excluir" /></a> 
        		</td>
        	</tr> 
	<?php endforeach; ?> 
</table> 