<table class="tableItems"> 
<tr> 
    <th>Tipo de Embarque</th> 
    <th><a href="<?php echo $this->url(array('action'=>'add'))?>"><img src="/images/add4.png" alt="Adicionar" title="Adicionar" /></a>
    </th> 
</tr> 
<?php foreach($this->tipoEmbarque as $tipoEmbarque) : ?>
<?php @$style=($style=='evenRow') ? 'oddRow' : 'evenRow' ;?> 
<tr class="<?php echo @$style;?>"> 
    <td><?php echo $this->escape($tipoEmbarque->tipo);?></td> z
    <td style="min-width:30pt;text-align: right;background-color: transparent;">
        <a href="<?php echo $this->url(array('action'=>'edit'))?>/id/<?php echo $tipoEmbarque->id;?>"><img src="/images/edit.png" alt="Editar" title="Editar" /></a> 
        <a href="<?php echo $this->url(array('action'=>'del'))?>/id/<?php echo $tipoEmbarque->id;?>"><img src="/images/del.png" alt="Excluir" title="Excluir" /></a> 
	</td>
</tr> 
<?php endforeach; ?> 
</table> 