<?php if ($this->ncms) :?> 
	<p>Tem certeza que deseja deletar o NCMS
	  '<?php echo $this->escape($this->ncms->codigo); ?>' (<?php echo $this->escape($this->ncms->descricao); ?>)? 
	</p> 
	<form action="<?php echo $this->url(array('action'=>'del')); ?>" method="post"> 
		<div> 
		  <input type="hidden" name="id" value="<?php echo $this->ncms->id; ?>" /> 
		  <input type="submit" class="button"  name="del" value="Sim" /> 
		  <input type="submit" class="button2" name="del" value="Não" /> 
		</div> 
	</form> 
<?php else: ?> 
	<p>NCMS não pôde ser encontrado.</p> 
<?php endif;?> 