<table class="tableItems"> 
<tr> 
    <th>Codigo</th> 
    <th>Descricao</th> 
    <th>&nbsp;<a href="/ncms/add"><img src="/images/add4.png" alt="Adicionar" title="Adicionar" /></a></th> 
</tr> 
<?php foreach($this->ncms as $ncms) : ?>
<?php @$style=($style=='evenRow') ? 'oddRow' : 'evenRow' ;?> 
<tr class="<?php echo @$style;?>"> 
    <td>&nbsp;<?php echo $this->escape($ncms->codigo);?>&nbsp;</td> 
    <td>&nbsp;<?php echo $this->escape($ncms->descricao);?>&nbsp;</td> 
    <td style="min-width:30pt;text-align: right;background-color: transparent;">
        <a href="/ncms/edit/id/<?php echo $ncms->id;?>"><img src="/images/edit.png" alt="Editar" title="Editar" /></a> 
        <a href="/ncms/del/id/<?php echo $ncms->id;?>"><img src="/images/del.png" alt="Excluir" title="Excluir" /></a> 
	</td>
</tr> 
<?php endforeach; ?> 
</table> 