<?php if ($this->material) :?> 
	<p>Tem certeza que deseja deletar a material
	  '<?php echo $this->escape($this->material->material); ?>'? 
	</p> 
	<form action="<?php echo $this->url(array('action'=>'del')); ?>" method="post"> 
		<div> 
		  <input type="hidden" name="id" value="<?php echo $this->material->id; ?>" /> 
		  <input type="submit" class="button"  name="del" value="Sim" /> 
		  <input type="submit" class="button2" name="del" value="Não" /> 
		</div> 
	</form> 
<?php else: ?> 
	<p>Material não pôde ser encontrada.</p> 
<?php endif;?> 