<table style="width:100%"> 
<tr> 
    <th>Material</th> 
    <th class="editDelCell"><a href="/materiais/add"><img src="/images/add4.png" alt="Adicionar" title="Adicionar" /></a></th>
</tr> 
<?php foreach($this->material as $material) : ?>
<?php @$style=($style=='evenRow') ? 'oddRow' : 'evenRow' ;?> 
<tr class="<?php echo @$style;?>"> 
    <td><?php echo $this->escape($material->material);?></td> 
    <td style="min-width:30pt;text-align: right;background-color: transparent;">
        <a href="/materiais/edit/id/<?php echo $material->id;?>"><img src="/images/edit.png" alt="Editar" title="Editar" /></a> 
        <a href="/materiais/del/id/<?php echo $material->id;?>"><img src="/images/del.png" alt="Excluir" title="Excluir" /></a> 
	</td>
</tr> 
<?php endforeach; ?> 
</table> 