<?php if ($this->cliente) :?> 
	<p>Tem certeza que deseja deletar a transportadora
	  '<?php echo $this->escape($this->cliente->nome); ?>'?
	</p> 
	<form action="<?php echo $this->url(array('action'=>'del')); ?>" method="post"> 
		<div> 
		  <input type="hidden" name="id" value="<?php echo $this->cliente->id; ?>" />
		  <input type="submit" class="button"  name="del" value="Sim" /> 
		  <input type="submit" class="button2" name="del" value="Não" /> 
		</div> 
	</form> 
<?php else: ?> 
	<p>Cliente não pôde ser encontrado.</p>
<?php endif;?> 