<?php if ($this->tipoProduto) :?> 
	<p>Tem certeza que deseja deletar o tipo de produto
	  '<?php echo $this->escape($this->tipoProduto->tipo); ?>'? 
	</p> 
	<form action="<?php echo $this->url(array('action'=>'del')); ?>" method="post"> 
		<div> 
		  <input type="hidden" name="id" value="<?php echo $this->tipoProduto->id; ?>" /> 
		  <input type="submit" class="button"  name="del" value="Sim" /> 
		  <input type="submit" class="button2" name="del" value="Não" /> 
		</div> 
	</form> 
<?php else: ?> 
	<p>Tipo de produto não pôde ser encontrado.</p> 
<?php endif;?> 