<?php if ($this->tamanho) :?> 
	<p>Tem certeza que deseja deletar a tamanho
	  '<?php echo $this->escape($this->tamanho->tamanho); ?>'? 
	</p> 
	<form action="<?php echo $this->url(array('action'=>'del')); ?>" method="post"> 
		<div> 
		  <input type="hidden" name="id" value="<?php echo $this->tamanho->id; ?>" /> 
		  <input type="submit" class="button"  name="del" value="Sim" /> 
		  <input type="submit" class="button2" name="del" value="Não" /> 
		</div> 
	</form> 
<?php else: ?> 
	<p>Tamanho não pôde ser encontrad.</p> 
<?php endif;?> 