<table class="tableItems"> 
<tr> 
    <th>Tamanho</th> 
    <th>&nbsp;<a href="<?php echo $this->url(array('action'=>'add'))?>"><img src="/images/add4.png" alt="Adicionar" title="Adicionar" /></a></th> 
</tr> 
<?php foreach($this->tamanho as $tamanho) : ?>
<?php @$style=($style=='evenRow') ? 'oddRow' : 'evenRow' ;?> 
<tr class="<?php echo @$style;?>"> 
    <td>&nbsp;<?php echo $this->escape($tamanho->tamanho);?>&nbsp;</td> 
    <td style="min-width:30pt;text-align: right;background-color: transparent;">
        <a href="<?php echo $this->url(array('action'=>'edit'))?>/id/<?php echo $tamanho->id;?>"><img src="/images/edit.png" alt="Editar" title="Editar" /></a> 
        <a href="<?php echo $this->url(array('action'=>'del'))?>/id/<?php echo $tamanho->id;?>"><img src="/images/del.png" alt="Excluir" title="Excluir" /></a> 
	</td>
</tr> 
<?php endforeach; ?> 
</table> 