<?php if ($this->estacao) :?> 
	<p>Tem certeza que deseja deletar a estação
	  '<?php echo $this->escape($this->estacao->estacao); ?>'? 
	</p> 
	<form action="<?php echo $this->url(array('action'=>'del')); ?>" 
	method="post"> 
		<div> 
		  <input type="hidden" name="id" value="<?php echo $this->estacao->id; ?>" /> 
		  <input type="submit" class="button"  name="del" value="Sim" /> 
		  <input type="submit" class="button2" name="del" value="Não" /> 
		</div> 
	</form> 
<?php else: ?> 
	<p>Estação não pode ser encontrada.</p> 
<?php endif;?> 