<table class="tableItems"> 
<tr> 
    <th>Estação</th> 
    <th>&nbsp;
    	<a href="<?php echo $this->url(array('action'=>'add'));?>">
    		<img src="/images/add4.png" alt="Adicionar" title="Adicionar" />
    	</a>
    </th> 
</tr> 
<?php foreach($this->estacoes as $est) : ?>
<?php @$style=($style=='evenRow') ? 'oddRow' : 'evenRow' ;?> 
<tr class="<?php echo @$style;?>"> 
    <td>&nbsp;<?php echo $this->escape($est->estacao);?>&nbsp;</td> 
    <td style="min-width:30pt;text-align: right;background-color: transparent;">
		        <a href="<?php echo $this->url(array('controller'=>'estacao',
					'action'=>'edit', 'id'=>$est->id));?>"><img src="/images/edit.png" alt="Editar" title="Editar" /></a> 
		            
		        <a href="<?php echo $this->url(array('controller'=>'estacao',  
		            'action'=>'del', 'id'=>$est->id));?>"><img src="/images/del.png" alt="Excluir" title="Excluir" /></a> 
	</td>
</tr> 
<?php endforeach; ?> 
</table> 